#!/bin/sh /etc/rc.common

START=61

USE_PROCD=1
NAME=umap-agent
PROG=/usr/sbin/umapd

start_service() {
	local interfaces=$(uci -q get umapd.@agent[0].interface)
	local radios=$(uci -q get umapd.@agent[0].radio)
	local devices

	. /lib/functions/network.sh

	for interface in ${interfaces:-lan}; do
		local device
		network_get_device device "$interface" && \
			[ -e "/sys/class/net/$device" ] && \
			devices="${devices:+$devices }$device"
	done

	[ -n "$devices" ] || {
		echo "Unable to determine devices to operate on" >&2
		exit 1
	}

	[ -n "$radios" ] || {
		echo "Unable to determine radios to manage" >&2
		exit 1
	}

	procd_open_instance

	procd_set_param respawn 30 3 0
	procd_set_param stderr 1
	procd_set_param stdout 1

	procd_set_param command "$PROG"

    for ifname in $devices; do
        procd_append_param command --interface "$ifname"
    done

    for radio in $radios; do
        procd_append_param command --radio "$radio"
    done

	procd_set_param respawn
	procd_close_instance
}
